# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    app.command.manage_category.class: AppBundle\Command\ManageCategoryCommand
    app.command.manage_order_promotion.class: AppBundle\Command\ManageOrderPromotionCommand
    app.command.manage_product.class: AppBundle\Command\ManageProductCommand
    app.fixture.load.class: AppBundle\DataFixtures\LoadFixtures
    app.repository.category.class: AppBundle\Entity\Repository\CategoryRepository
    app.repository.order_promotion.class: AppBundle\Entity\Repository\OrderPromotionRepository
    app.repository.product.class: AppBundle\Entity\Repository\ProductRepository
    app.service.order_service.class: AppBundle\Service\OrderService
    app.service.managers_command.class: AppBundle\Service\ManagersCommandService
    app.processor.order_promotion.class: AppBundle\Processor\OrderPromotion
    app.repository.category_freebie_promotion.class: AppBundle\Entity\Repository\CategoryFreebiePromotionRepository

services:
    _defaults:
        autowire: true
        # Normally I prefer to have control over the services, so I disabled autoconfigure.
        autoconfigure: false
        public: false

    ##### Doctrine entity repositories

    app.repository.category:
        class: '%app.repository.category.class%'
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\Category ]
        tags:
            - { name: 'doctrine.repository_service' }

    app.repository.product:
        class: '%app.repository.product.class%'
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\Product ]
        tags:
            - { name: 'doctrine.repository_service' }

    app.repository.order_promotion:
        class: '%app.repository.order_promotion.class%'
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\OrderPromotion ]
        tags:
            - { name: 'doctrine.repository_service' }

    app.repository.category_freebie_promotion:
        class: '%app.repository.category_freebie_promotion.class%'
        public: true
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [ AppBundle\Entity\CategoryFreebiePromotion ]
        tags:
            - { name: 'doctrine.repository_service' }

    ##### Commands

    app.command.manage_category:
        class: '%app.command.manage_category.class%'
        public: true
        calls:
            - [setCategoryRepository, ['@app.repository.category']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: 'console.command' }

    app.command.manage_product:
        class: '%app.command.manage_product.class%'
        public: true
        calls:
            - [setCategoryRepository, ['@app.repository.category']]
            - [setProductRepository, ['@app.repository.product']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: 'console.command' }

    app.command.manage_order_promotion:
        class: '%app.command.manage_order_promotion.class%'
        public: true
        calls:
            - [setCategoryRepository, ['@app.repository.category']]
            - [setProductRepository, ['@app.repository.product']]
            - [setManagersCommandService, ['@app.service.managers_command']]
            - [setOrderPromotionRepository, ['@app.repository.order_promotion']]
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
        tags:
            - { name: 'console.command' }

    ##### Services

    app.service.order_service:
        class: '%app.service.order_service.class%'
        public: true
        calls:
            - [setProductRepository, ['@app.repository.product']]

    app.service.managers_command:
        class: '%app.service.managers_command.class%'
        public: true
        calls:
            - [setCategoryRepository, ['@app.repository.category']]
            - [setProductRepository, ['@app.repository.product']]
            - [setOrderPromotionRepository, ['@app.repository.order_promotion']]

    ##### Fixtures

    app.fixture.load:
        class: '%app.fixture.load.class%'
        public: true
        tags:
            - { name: 'doctrine.fixture.orm' }

    ##### Processors

    app.processor.order_promotion:
        class: '%app.processor.order_promotion.class%'
        public: true
        calls:
            - [setProductRepository, ['@app.repository.product']]
            - [setOrderPromotionRepository, ['@app.repository.order_promotion']]
